# dark-mode: true
# --> Catppuccin (Mocha)
# bg "#1e1e2e"
# fg "#cdd6f4"

# Colors
# rosewater "#f5e0dc"
# flamingo "#f2cdcd"
# rosewater "#f5e0dc"
# pink "#f5c2e7"
# mauve "#cba6f7"
# red "#f38ba8"
# maroon "#eba0ac"
# peach "#fab387"
# yellow "#f9e2af"
# green "#a6e3a1"
# teal "#94e2d5"
# sky "#89dceb"
# sapphire "#74c7ec"
# blue "#89b4fa"
# lavender "#b4befe"

# Surfaces and overlays
# subtext_1 "#a6adc8"
# subtext_0 "#bac2de"
# overlay_2 "#9399b2"
# overlay_1 "#7f849c"
# overlay_0 "#6c7086"
# surface_2 "#585b70"
# surface_1 "#45475a"
# surface_0 "#313244"
# mantle "#181825"
# crust "#11111b"
user-input-color: "#cdd6f4"
tool-output-color: "#89b4fa"
tool-error-color: "#f38ba8"
tool-warning-color: "#fab387"
assistant-output-color: "#a6e3a1"
completion-menu-color: "#f5e0dc"
completion-menu-bg-color: "#45475a"
completion-menu-current-color: "#45475a"
completion-menu-current-bg-color: "#f5e0dc"
